-- ERAM Category Fix Script
-- Generated by CategoryDebugger
-- Generated at: 2025-10-03T20:31:23.795Z

-- WARNING: Review this script carefully before executing!
-- Make a backup of your database first!

-- Remove unused categories (optional)
-- Only execute if you are sure these categories are not needed

-- DELETE FROM categorias WHERE id = 1; -- "Sin Categoría"
